name: fetch-latest-problem

# schedule is set automatically by script
on:
  workflow_dispatch:
  schedule:
    - cron: '5 18 9 7 *'
    - cron: '5 21 10 9 *'
    - cron: '5 0 18 9 *'
    - cron: '5 3 25 9 *'
    - cron: '5 6 2 10 *'
    - cron: '5 9 8 10 *'
    - cron: '5 12 15 10 *'
# end of schedule
    
permissions:
  actions: write

jobs:
  fetch-problem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: pip install -r requirements.txt
      - run: python -m euler_binder
      - uses: actions-x/commit@v6
        with:
          files: problems http_cache.sqlite .github/workflows/fetch.yml
