name: fetch-latest-problem

# schedule is set automatically by script
on:
  workflow_dispatch:
  schedule:
    - cron: '5 7 12 3 *'
    - cron: '5 10 19 3 *'
    - cron: '5 13 25 3 *'
    - cron: '5 16 1 4 *'
    - cron: '5 16 1 4 *'
# end of schedule
    
jobs:
  fetch-problem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - uses: actions/setup-python@v3
      - run: pip install -r requirements.txt
      - run: python -m euler_binder
      - uses: actions-x/commit@v6
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          files: problems http_cache.sqlite .github/workflows/fetch.yml
