name: fetch-latest-problem

# schedule is set automatically by script
on:
  workflow_dispatch:
  schedule:
    - cron: '5 16 27 5 *'
    - cron: '5 19 3 6 *'
    - cron: '5 22 10 6 *'
    - cron: '5 1 18 6 *'
    - cron: '5 4 25 6 *'
    - cron: '5 7 2 7 *'
    - cron: '5 10 9 7 *'
# end of schedule
    
jobs:
  fetch-problem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - uses: actions/setup-python@v3
      - run: pip install -r requirements.txt
      - run: python -m euler_binder
      - uses: actions-x/commit@v6
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          files: problems http_cache.sqlite .github/workflows/fetch.yml
