name: fetch-latest-problem

# schedule is set automatically by script
on:
  workflow_dispatch:
  schedule:
    - cron: '5 15 2 7 *'
    - cron: '5 18 9 7 *'
# end of schedule
    
jobs:
  fetch-problem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: pip install -r requirements.txt
      - run: python -m euler_binder
      - uses: actions-x/commit@v6
        with:
          files: problems http_cache.sqlite .github/workflows/fetch.yml
